import { zodResolver } from '@hookform/resolvers/zod';
import Head from "next/head";
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form';
import { toast } from "sonner"
import * as z from "zod"

import { Button } from "@/components/ui/Button";
import { Card, CardContent, CardHeader } from '@/components/ui/Card';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/Form';
import { Input } from "@/components/ui/Input";

import { siteConfig } from "@/constant/config";
import auth from '@/integrations/auth';
import cookie from '@/utils/cookie';

const LoginPage = () => {
  const { push: navigate } = useRouter();

  const formSchema = z.object({
    email: z.string().min(1, "Field wajib diisi"),
    password: z.string().min(1, "Field wajib diisi")
  });

  const form = useForm({
    resolver: zodResolver(formSchema),
    defaultValues: {
      email: 'kminchelle',
      password: '0lelplR',
    },
  });

  async function onSubmit(formValues) {
    auth.login(formValues).then((response) => {
      cookie.set('utoken', JSON.stringify(response));
      navigate('/')
    }).catch(() => {
      toast('Email atau Password salah.');
    });
  }

  return (
    <>
      <Head>
        <title>Login - {siteConfig.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="h-screen flex relative px-2 lg:max-w-7xl lg:gap-x-8">

        <Card className="sm:w-[350px] m-auto">
          <CardHeader>
            <div className="w-full flex justify-center items-center flex-col">
              <div className="flex justify-center items-center">
                <img src="/images/logo.png" alt="simple-cart-logo" className="w-20" />
                <div className="flex flex-col">
                  <h1 className="text-2xl font-semibold tracking-tight ps-2">Login</h1>
                  <h3 className="text-base ps-2">Simple cart.</h3>
                </div>
              </div>
            </div>
          </CardHeader>
          <CardContent>

            <div className="mx-auto flex flex-col justify-center">
              <div className="flex flex-col space-y-2 text-center">
                <p className="text-sm text-muted-foreground">Enter your email and password below to login</p>
              </div>
              <div className="grid gap-6 mt-10">
                <Form {...form}>
                  <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
                    <FormField
                      control={form.control}
                      name="email"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-black">Email*</FormLabel>
                          <FormControl>
                            <Input {...field} type="text" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="password"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-black">Password*</FormLabel>
                          <FormControl>
                            <Input {...field} type="password" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <div className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2">
                      <Button className="w-full" type="submit">Login</Button>
                    </div>
                  </form>
                </Form>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </>
  )
}


export default LoginPage;
